### ISSUE TITLE
the api key

### ISSUE THREAD

**Issue by assassinliujie** [admineral/GPT4-Vision-React-Starter#3]
I found that after deployment, it is possible to retrieve your API key from the website frontend through the console. It should be encrypted for security reasons.

**Comment by assassinliujie** [comment]
![8c0d7ec5066fa10bea42bc175818507f](https://github.com/admineral/GPT4-Vision-React-Starter/assets/68693675/d3cc4035-9a73-4399-b5a4-e71274dbfcdc)

**Comment by admineral** [comment]
Thank you for the note! For this reason, I actually removed the key, I am surprised that you still have access to it. This repo will be revised tomorrow

**Comment by admineral** [comment]
Merged the Refactor
